package lang.practice;

/*
For every Object a unique number generated by JVM which is nothing but hashcode
hashcode won't represent address of object
JVM will use hashcode while saving Objects into Hashing related datastructures like HashTable, hashMap, HashSet etc.
The main advantage of saving Objects based on hashcode is to retrieve or search operation will become easy(Hashing is the best technique till date)
Hashcode is generated based on address using internal Object class Hashcode method
*/

public class HashCodeOverriding {

	private int i;
	HashCodeOverriding(int i)
	{
		this.i = i;
	}
	@Override
	public int hashCode() {
		return i;
	}
	public static void main(String[] args) {
		
		HashCodeOverriding hc1 = new HashCodeOverriding(10);
		HashCodeOverriding hc2 = new HashCodeOverriding(101);
		System.out.println(hc1);
		System.out.println(hc2);
	}

}
